### ISSUE TITLE
Field type too small for data

### ISSUE THREAD

**Issue by alanski66** [augmentations/craft-json#1]
Where can I alter the field type to store more json?
I get an error on large json data: should contain at most 65,535 characters and entry will not save.

Ive changed the field in the content table to MEDIUMTEXT but this hasnt solved it

**Comment by alanski66** [comment]
Temp fix:
        $bytes = "16777215";
        return Schema::TYPE_STRING . "({$bytes})";

**Comment by joshuabaker** [comment]
Wow, that’s a massive JSON object.

This somewhat relates to Craft’s schema settings for JSON. In future, when support is included in Craft itself, we’ll update this to include more JSON-type features.

Thanks for posting your intermediate fix. 🙏🏻 

I’ve made a note to expand testing to larger JSON objects in future.

**Comment by alanski66** [comment]
Its not that big just over the limit:)

**Comment by cliveportman** [comment]
> Temp fix: $bytes = "16777215"; return Schema::TYPE_STRING . "({$bytes})";

Hi. Where did you put this?

**Comment by alanski66** [comment]
vendor/augmentations/craft-json/src/fields/JsonField.php
 public function getContentColumnType(): string
    {
        // N.B. Craft does not officially support JSON yet
        // https://github.com/craftcms/cms/issues/7951
        $bytes = "16777215";
        return Schema::TYPE_STRING . "({$bytes})";
        //return Schema::TYPE_TEXT;
    }

**Comment by cliveportman** [comment]
Thanks. I've got an identical problem with a lot of JSON data stored in a plain text field.
@joshuabaker - I don't think this issue should be closed. Or is there a branch we can use with this fix added?

**Comment by joshuabaker** [comment]
As per https://github.com/augmentations/craft-json/issues/2#issuecomment-1344287325, I’m going to close this issue. The JSON field plugin will no longer be maintained.

For instances where you expect to be dealing with large JSON sizes in excess of what’s sensible to store in a `TEXT` field I would recommend you instead store these as uploaded assets and parse those in the template or client.
