### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by alanski66** [augmentations/craft-json#2]
I realise how much i depend on this field for a particular project. Will there be a Craft 4 version?

**Comment by joshuabaker** [comment]
@joomkit This is the first request for it. We’ll try and get support for Craft 4 as soon as possible. 👍🏻

**Comment by alanski66** [comment]
Awseome - I'm not in a massive hurry (famous last words)

**Comment by justenh** [comment]
@joshuabaker We have several projects that would also need this plugin to be updated before we can move them to Craft 4. Thanks for a great plugin!

**Comment by joshuabaker** [comment]
We’ve also got some sites that depend on this. Update is currently planned for November.

**Comment by alanski66** [comment]
Any update on this?

**Comment by joshuabaker** [comment]
@joomkit Thanks for your patience. I’m sorry to report that we’ve cancelled plans for a Craft 4 version of this field and will not be maintaining it further.

I’ll update the repository with the notice shared on the [Plugin Store entry](https://plugins.craftcms.com/json?craft3). Following Andrew’s recent release of [Code Field](https://plugins.craftcms.com/codefield) that’s available for free it seemed unreasonable to continue maintaining and charging for something equivalent. Both use the `TEXT` column type so will be interoperable.
